a = input('enter the first number')
a = int(a)
b = input('enter the second number')
b = int(b)
print("addition",a + b)
print("subtraction",a - b)
print("multiplication",a * b)
print("division",a / b)